### PR TITLE
Fix bug where client sometimes fails to receive current user's profile.

### LINKED ISSUE #15: Profile ocassionally does not attach to user
There is a problem after logout/login the profile schema is not attached to the user. This unfortunately happens only sometimes, the refresh solves the problem. Open dev tools and check with Meteor.user().profile, probably the full profile shown only with 'invitedBoards' property is returned. Try to relogin, check the profile again. If property still visible then try again. It usually happens after first relogin to me, but used to happen on the third one as well..
- a tip: if cannot reproduce the problem, after login try to click a board and then relogin again.
If empty object is displayed try refresh and it's solved.

EDIT: If reproduced the issue notice that this also causes shortcuts for starred boards to dissapear, which are also stored in the profile

### PR DESCRIPTION
**Pull request by dwrensha**
Fixes #15.

### CODE REVIEW

**Comment by dwrensha** [comment]
Actually, please hold off on merging this. I just noticed that it breaks the little green presence indicators by the user avatars. :/

**Comment by dwrensha** [comment]
This should be OK now.

**Comment by xet7** [comment]
@dwrensha 


Hi,
using Wekan standalone version (not Sandstorm) with node version 0.10.48, when I use these scripts to rebuild and run wekan:

```bash
# wefork-build.sh

rm -rf wekan
git clone https://github.com/wefork/wekan
cd wekan
# OPTIONAL: test pull request
git checkout -b dwrensha-profile-bugfix devel
git pull https://github.com/dwrensha/wekan.git profile-bugfix
# THESE 2 ONLY ON FIRST INSTALL
#sudo npm install -g node-gyp
#sudo npm install -g fibers
npm install
meteor update --release 1.3.5.1
rm -rf .build
meteor build .build --directory
cd .build/bundle/programs/server
npm install
cd ../../../../..
echo "Build done. Starting wefork server."
./wefork.sh

# wefork.sh

cd ~/repos/wekan/.build/bundle
export MONGO_URL='mongodb://127.0.0.1:27017/admin'
export ROOT_URL='https://wekan.example.com'
export MAIL_URL='smtp://user:pass@mailserver.example.com:25/'
export PORT=9595
node main.js
```

I use this Caddyfile on Ubuntu 16.04 server:

```
wekan.example.com {
        proxy / 127.0.0.1:9595 {
                websocket
        }
}
```

And this service file for Caddy:

```bash
# /etc/systemd/system/caddy@.service

; see `man systemd.unit` for configuration details
; the man section also explains *specifiers* `%x`

[Unit]
Description=Caddy HTTP/2 web server %I
Documentation=https://caddyserver.com/docs
After=network-online.target
Wants=network-online.target
Wants=systemd-networkd-wait-online.service

[Service]
; run user and group for caddy
User=user
Group=user
ExecStart=/home/user/caddy/caddy -conf=/home/user/caddy/Caddyfile -agree -email="admin@example.com"
Restart=on-failure
RestartSec=10
; create a private temp folder that is not shared with other processes
PrivateTmp=true
; limit the number of file descriptors, see `man systemd.exec` for more limit settings
LimitNOFILE=8192

[Install]
WantedBy=multi-user.target
```

Service was installed with:

```
sudo systemctl daemon-reload
sudo systemctl start caddy@user
sudo systemctl enable caddy@user
```

A) When I login normally, it logins to Wekan

B) But when I did this:

1) Create public board on Wekan that is running behing Caddy webserver
on url:
https://wekan.example.com/b/o7LAibK2RYwpTAqEj/test

2) Click login link on public board
3) Try to Login, did not work
4) I got this error shown below on Firefox Javascript console, and was unable to login:

```javascript
Uncaught Error: Expected to find a document to change
    at Object.e [as update] (https://wekan.example.com/04f348cecd83b637715e27df43bba96943b20809.js?meteor_js_resource=true:93:3642)
    at Object.r.(anonymous function) [as update] (https://wekan.example.com/04f348cecd83b637715e27df43bba96943b20809.js?meteor_js_resource=true:85:9855)
    at https://wekan.example.com/04f348cecd83b637715e27df43bba96943b20809.js?meteor_js_resource=true:85:18026
    at Array.forEach (native)
    at Function.A.each.A.forEach (https://wekan.example.com/04f348cecd83b637715e27df43bba96943b20809.js?meteor_js_resource=true:1:865)
    at https://wekan.example.com/04f348cecd83b637715e27df43bba96943b20809.js?meteor_js_resource=true:85:18005
    at Function.A.each.A.forEach (https://wekan.example.com/04f348cecd83b637715e27df43bba96943b20809.js?meteor_js_resource=true:1:1009)
    at o._performWrites (https://wekan.example.com/04f348cecd83b637715e27df43bba96943b20809.js?meteor_js_resource=true:85:17961)
    at o._flushBufferedWrites (https://wekan.example.com/04f348cecd83b637715e27df43bba96943b20809.js?meteor_js_resource=true:85:17762)
    at o._livedata_data (https://wekan.example.com/04f348cecd83b637715e27df43bba96943b20809.js?meteor_js_resource=true:85:17149)
```

5) I did get these errors on node.js server:

```javascript
Exception in queued task: Error: Removed nonexistent document npaSKbnsZGYn4ewrq-9g9GvNrENowFF6rcu
    at SessionCollectionView.removed (packages/ddp-server/livedata_server.js:202:17)
    at Session.removed (packages/ddp-server/livedata_server.js:391:10)
    at Subscription.removed (packages/ddp-server/livedata_server.js:1272:19)
    at removed (packages/cottz:publish-relations/lib/server/cursor/cursor.js:52:13)
    at packages/mongo/observe_multiplex.js:183:30
    at Function._.each._.forEach (packages/underscore/underscore.js:108:1)
    at Object.task (packages/mongo/observe_multiplex.js:177:9)
    at [object Object]._.extend._run (packages/meteor/fiber_helpers.js:147:1)
    at packages/meteor/fiber_helpers.js:125:1
Exception in queued task: Error: Could not find element with id npaSKbnsZGYn4ewrq-LoqhPiYpYaZjCx5Si to change
    at SessionCollectionView.changed (packages/ddp-server/livedata_server.js:188:13)
    at Session.changed (packages/ddp-server/livedata_server.js:400:10)
    at Subscription.changed (packages/ddp-server/livedata_server.js:1253:19)
    at changed (packages/cottz:publish-relations/lib/server/cursor/cursor.js:44:13)
    at packages/mongo/observe_multiplex.js:183:30
    at Function._.each._.forEach (packages/underscore/underscore.js:108:1)
    at Object.task (packages/mongo/observe_multiplex.js:177:9)
    at [object Object]._.extend._run (packages/meteor/fiber_helpers.js:147:1)
    at packages/meteor/fiber_helpers.js:125:1
Exception in queued task: Error: Removed nonexistent document npaSKbnsZGYn4ewrq-LoqhPiYpYaZjCx5Si
    at SessionCollectionView.removed (packages/ddp-server/livedata_server.js:202:17)
    at Session.removed (packages/ddp-server/livedata_server.js:391:10)
    at Subscription.removed (packages/ddp-server/livedata_server.js:1272:19)
    at removed (packages/cottz:publish-relations/lib/server/cursor/cursor.js:52:13)
    at packages/mongo/observe_multiplex.js:183:30
    at Function._.each._.forEach (packages/underscore/underscore.js:108:1)
    at Object.task (packages/mongo/observe_multiplex.js:177:9)
    at [object Object]._.extend._run (packages/meteor/fiber_helpers.js:147:1)
    at packages/meteor/fiber_helpers.js:125:1
```

6) When I did
6.1) Rebuild wefork
6.2) Go to board public link
6.3) Used login link on board to login
6.4) It did not show any errors on serverside anymore, but on clientside Firefox Javascript console it showed these errors below
6.5) Although login button did not work at first, when when checking source code I noticed it had logged me in anyway to All boards page.

```javascript
04f348c….js?meteor_js_resource=true:93 Uncaught Error: Expected to find a document to change
    at Object.e [as update] (https://wekan.example.com/04f348cecd83b637715e27df43bba96943b20809.js?meteor_js_resource=true:93:3642)
    at Object.r.(anonymous function) [as update] (https://wekan.example.com/04f348cecd83b637715e27df43bba96943b20809.js?meteor_js_resource=true:85:9855)
    at https://wekan.example.com/04f348cecd83b637715e27df43bba96943b20809.js?meteor_js_resource=true:85:18026
    at Array.forEach (native)
    at Function.A.each.A.forEach (https://wekan.example.com/04f348cecd83b637715e27df43bba96943b20809.js?meteor_js_resource=true:1:865)
    at https://wekan.example.com/04f348cecd83b637715e27df43bba96943b20809.js?meteor_js_resource=true:85:18005
    at Function.A.each.A.forEach (https://wekan.example.com/04f348cecd83b637715e27df43bba96943b20809.js?meteor_js_resource=true:1:1009)
    at o._performWrites (https://wekan.example.com/04f348cecd83b637715e27df43bba96943b20809.js?meteor_js_resource=true:85:17961)
    at o._flushBufferedWrites (https://wekan.example.com/04f348cecd83b637715e27df43bba96943b20809.js?meteor_js_resource=true:85:17762)
    at o._livedata_data (https://wekan.example.com/04f348cecd83b637715e27df43bba96943b20809.js?meteor_js_resource=true:85:17149)e @ 04f348c….js?meteor_js_resource=true:93r.(anonymous function) @ 04f348c….js?meteor_js_resource=true:85(anonymous function) @ 04f348c….js?meteor_js_resource=true:85A.each.A.forEach @ 04f348c….js?meteor_js_resource=true:1(anonymous function) @ 04f348c….js?meteor_js_resource=true:85A.each.A.forEach @ 04f348c….js?meteor_js_resource=true:1_performWrites @ 04f348c….js?meteor_js_resource=true:85_flushBufferedWrites @ 04f348c….js?meteor_js_resource=true:85_livedata_data @ 04f348c….js?meteor_js_resource=true:85e.connection._livedata_data @ 04f348c….js?meteor_js_resource=true:182o @ 04f348c….js?meteor_js_resource=true:85(anonymous function) @ 04f348c….js?meteor_js_resource=true:85A.each.A.forEach @ 04f348c….js?meteor_js_resource=true:1t.socket.onmessage @ 04f348c….js?meteor_js_resource=true:85r.dispatchEvent @ 04f348c….js?meteor_js_resource=true:83C._dispatchMessage @ 04f348c….js?meteor_js_resource=true:83C._didMessage @ 04f348c….js?meteor_js_resource=true:83o.ws.onmessage @ 04f348c….js?meteor_js_resource=true:83
04f348c….js?meteor_js_resource=true:93 Uncaught Error: Expected to find a document to change(…)e @ 04f348c….js?meteor_js_resource=true:93r.(anonymous function) @ 04f348c….js?meteor_js_resource=true:85(anonymous function) @ 04f348c….js?meteor_js_resource=true:85A.each.A.forEach @ 04f348c….js?meteor_js_resource=true:1(anonymous function) @ 04f348c….js?meteor_js_resource=true:85A.each.A.forEach @ 04f348c….js?meteor_js_resource=true:1_performWrites @ 04f348c….js?meteor_js_resource=true:85_flushBufferedWrites @ 04f348c….js?meteor_js_resource=true:85_livedata_data @ 04f348c….js?meteor_js_resource=true:85e.connection._livedata_data @ 04f348c….js?meteor_js_resource=true:182o @ 04f348c….js?meteor_js_resource=true:85(anonymous function) @ 04f348c….js?meteor_js_resource=true:85A.each.A.forEach @ 04f348c….js?meteor_js_resource=true:1t.socket.onmessage @ 04f348c….js?meteor_js_resource=true:85r.dispatchEvent @ 04f348c….js?meteor_js_resource=true:83C._dispatchMessage @ 04f348c….js?meteor_js_resource=true:83C._didMessage @ 04f348c….js?meteor_js_resource=true:83o.ws.onmessage @ 04f348c….js?meteor_js_resource=true:83
```

**Comment by dwrensha** [comment]
Ah, interesting. I was able to reproduce that error. I've added a commit that avoids it, but I'm going to close this PR in favor of #25.

**Pull request closed without merging**
