### PR TITLE
Add checklist feature

### PR DESCRIPTION
**Pull request by lkisme**
Made a quick PR on wefork code base, will continue to test and refine the code, hope this will help.
The diff is identical with PR https://github.com/wekan/wekan/pull/630

### CODE REVIEW

**Comment by whittssg** [comment]
@lkisme When testing this I (and a few others) noticed that we couldn't get the Checklist Name edits to stick nor Checklist item edits to stick.

Adding the following in the checklists.jade file seemed to work:

Line 14:
+inlinedForm(classNames="js-edit-checklist-title" checklist = checklist)
_added checklist=checklist_
Line 46:
 +inlinedForm(classNames="js-edit-checklist-item" item = item checklist = checklist)
_added item = item checklist = checklist_

Thanks.

**Comment by jeremykraft** [comment]
I can't seem to "check" any of the items on the lists I create. Everything else works (create lists, add items, delete, etc...) now that I've made the two changes to checklists.jade as suggested by @whittssg ... Any ideas?

**Comment by whittssg** [comment]
@jeremykraft Did you include this at the bottom of your checklists.js:

BlazeComponent.extendComponent({
  toggleItem() {
    const checklist = this.currentData().checklist;
    const item = this.currentData().item;
    if (checklist && item && item._id) {
      checklist.toggleItem(item._id);
    }
  },
  events() {
    return [{
      'click .item .check-box': this.toggleItem,
    }];
  },
}).register('itemDetail');

**Comment by jeremykraft** [comment]
I did not... But that fixed it! Thank you! 
Where did that come from?...

**Comment by whittssg** [comment]
@jeremykraft Its on the original PR.. not sure why it didnt make it to this one.

**Comment by brylie** [comment]
@lkisme, will you please update this PR to fix the above issue?

**Comment by Serubin** [comment]
Was the issue fixed?

@xet7 Can we merge this guy in assuming the issue was fixed.

**Pull request merged**
